version: '3'
services:

  ackris-db:
    image: mysql:8.0
    hostname: ackris.db
    container_name: ackris-db-snapshot
    stdin_open: true
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=bookstore
      - MYSQL_PASSWORD=1bookstore!
      - MYSQL_DATABASE=bookstoredb
    command: --default-authentication-plugin=mysql_native_password

  ackris-web:
    build: .
    image: blue.sky/ackris-web:${TAG}
    hostname: ackris.web
    container_name: ackris-web-snapshot
    # http://docs.docker.com/compose/networking/
    command: -Dmysql.ipaddress=ackris-db -Dmysql.port=3306 -Dmysql.database=bookstoredb -Dmysql.username=bookstore -Dmysql.password=1bookstore!
    stdin_open: true
    tty: true
    ports:
      - "8070:8080"
      - "9990:9990"
    depends_on:
      - ackris-db

  swaggerui:
    image: schickling/swagger-ui
    hostname: swagger-ui
    container_name: swagger-ui-demo
    ports:
      - "81:80"
    environment:
      - API_URL=https://raw.githubusercontent.com/tecris/continuous-delivery/master/swagger/swagger.json
      #- API_URL=http://localhost:8080/bookstore/rest/swagger.json
