version: '3.4'
services:

  flyway-migrate:
    image: trivialis/maven:3
    container_name: flyway-migrate
    volumes:
      - ./:/opt/continuous-delivery
      - ~/.m2:/root/.m2
    entrypoint:
      - /wait-for-mysql.sh
      - ackris-db
      - mvn
      - -f
      - /opt/continuous-delivery/pom.xml
      - clean
      - -Ddatabase.host=ackris-db
      - flyway:migrate
    depends_on:
        - ackris-db

  maven-test:
    image: trivialis/maven:3
    container_name: maven-test
    volumes:
      - ./:/opt/continuous-delivery
      - ~/.m2:/root/.m2
    entrypoint:
      - mvn
      - -f
      - /opt/continuous-delivery/pom.xml
      - clean
      - verify
      - -Dmaven.test.failure.ignore=false
      - -Dtest.host=ackris-web
      - -Dtest.port=8080
