version: '2'
services:

  nexus:
    image: sonatype/nexus:2.12.0-01
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - /opt/docker_volumes/nexus-data:/sonatype-work
    networks:
      cd_net:
        ipv4_address: 172.16.238.10

  jenkins:
    image: casadocker/jenkins:1.651.1
    container_name: jenkins
    ports:
      - "8088:8080"
    extra_hosts:
      - "blue.sky:${DOCKER_IP}"
      - "docker.host:${DOCKER_IP}"
      - "nexus:172.16.238.10"
    networks:
      cd_net:
        ipv4_address: 172.16.238.20

  bluesky-registry:
    container_name: bluesky-registry
    restart: always
    image: registry:2
    ports:
      - 443:5000
    environment:
      # how to override configuration
      # https://docs.docker.com/registry/configuration/#override-specific-configuration-options
      # https://github.com/docker/distribution/blob/master/docs/configuration.md
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - /opt/docker_volumes/registry/blue.sky/data:/var/lib/registry
      - /opt/docker_volumes/registry/blue.sky/certs:/certs

networks:
  cd_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
