version: 2
jobs:
  build:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#machine
      image: circleci/classic:201711-01

    steps:
      - checkout

      - run:
          name: Build application
          command: mvn clean package

      - run:
          name: start stack
          command: |
            set -x
            TAG=snapshot docker-compose up -d ackris-db ackris-web
            sleep 10

      - run:
          name: apply db scripts
          command: mvn clean compile flyway:migrate

      - run:
          name: run tests
          command: mvn clean verify -Dmaven.test.failure.ignore=false -Dtest.port=8070
