version: 2
jobs:
  build:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#machine
      image: circleci/classic:201711-01

    steps:
      - checkout

      - run:
          name: start stack
          command: |
            set -x
            TAG=dev docker-compose up -d ackris-db ackris-web

      - run:
          name: apply db scripts
          command: TAG=dev docker-compose -f docker-compose.yaml -f docker-compose-jenkins.yaml -f docker-compose-cd.yaml up flyway-migrate

      - run:
          name: run tests
          command: docker-compose -f docker-compose.yaml -f docker-compose-jenkins.yaml -f docker-compose-cd.yaml up maven-test
