package org.terra.bs.entities;

// Generated Apr 25, 2014 12:34:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BookGenreId generated by hbm2java
 */
@Embeddable
public class BookGenreId implements java.io.Serializable {

    private int genreId;
    private int bookId;

    public BookGenreId() {
    }

    public BookGenreId(int genreId, int bookId) {
        this.genreId = genreId;
        this.bookId = bookId;
    }

    @Column(name = "GENRE_ID", nullable = false)
    public int getGenreId() {
        return this.genreId;
    }

    public void setGenreId(int genreId) {
        this.genreId = genreId;
    }

    @Column(name = "BOOK_ID", nullable = false)
    public int getBookId() {
        return this.bookId;
    }

    public void setBookId(int bookId) {
        this.bookId = bookId;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other)
            return true;
        if (other == null)
            return false;
        if (!(other instanceof BookGenreId))
            return false;
        BookGenreId castOther = (BookGenreId) other;

        return (this.getGenreId() == castOther.getGenreId()) && (this.getBookId() == castOther.getBookId());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getGenreId();
        result = 37 * result + this.getBookId();
        return result;
    }

}
