pipeline {
    agent {
        docker {
            image 'trivialis/maven:3'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Remove left overs from previous run (if any)') {
            steps {
                sh 'TAG=dev docker-compose rm -f'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Start services') {
           steps {
               sh 'TAG=dev docker-compose up -d ackris-db ackris-web'
           }
       }
       stage('Apply db changes') {
          steps {
              sh 'TAG=dev docker-compose -f docker-compose.yaml -f docker-compose-cd.yaml up flyway-migrate'
          }
       }
       stage('Run tests') {
          steps {
              sh 'docker-compose -f docker-compose.yaml -f docker-compose-cd.yaml up maven-test'
          }
       }
       stage('Stop services') {
          steps {
              sh 'TAG=dev docker-compose stop'
          }
      }
      stage('Remove containers') {
         steps {
             sh 'TAG=dev docker-compose rm -f'
         }
     }
    }
    post {
     always {
         junit 'target/failsafe-reports/**/*.xml'
     }
   }
}
