node {
   def mvnHome
   stage('Checkout code') {
      git 'https://github.com/tecris/continuous-delivery.git'
      mvnHome = tool 'M3'
   }
   stage('Build') {
      // Run the maven build
     sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
   }
   stage('Destroy old environment') {
     sh "TAG=dev docker-compose -H http://docker.host:4243 down"
   }
   stage('Build image & start new environment') {
     sh "TAG=dev docker-compose -H http://docker.host:4243 up -d ackris-db ackris-web"
     sh "sleep 5"
   }
   stage('Provision database') {
     sh "'${mvnHome}/bin/mvn' clean compile flyway:migrate -Ddatabase.host=docker.host"
   }
   stage('Run integration tests') {
     sh "'${mvnHome}/bin/mvn' clean verify -Dmaven.test.failure.ignore=false -Dtest.port=8070 -Dtest.host=docker.host"
   }
   stage('Destroy environment') {
     sh "TAG=dev docker-compose -H http://docker.host:4243 down"
   }
}
